import type { ActionItem, SentimentPoint } from "@shared/schema";

interface EmailPayload {
  to: string;
  subject: string;
  html: string;
}

export async function sendEmail(payload: EmailPayload): Promise<void> {
  const sendgridApiKey = process.env.SENDGRID_API_KEY;
  
  if (!sendgridApiKey) {
    console.warn("SENDGRID_API_KEY not set - email not sent");
    return;
  }

  try {
    const response = await fetch("https://api.sendgrid.com/v3/mail/send", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${sendgridApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        personalizations: [{ to: [{ email: payload.to }] }],
        from: { email: "noreply@meetmate.ai", name: "MeetMate AI" },
        subject: payload.subject,
        content: [{ type: "text/html", value: payload.html }],
      }),
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`SendGrid error: ${error.errors?.[0]?.message || response.statusText}`);
    }

    console.log(`Email sent successfully to ${payload.to}`);
  } catch (error) {
    console.error("Error sending email:", error);
    throw error;
  }
}

export function generateAnalysisEmail(
  meetingType: string,
  summary: string,
  decisions: string[],
  actionItems: ActionItem[],
  blockers: string[],
  sentiment: string
): string {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <h2 style="color: #0f172a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px;">
        Meeting Analysis: ${meetingType}
      </h2>
      
      <section style="margin: 20px 0;">
        <h3 style="color: #1e293b;">📋 Summary</h3>
        <p style="line-height: 1.6;">${summary}</p>
      </section>

      ${decisions.length > 0 ? `
        <section style="margin: 20px 0;">
          <h3 style="color: #1e293b;">✅ Decisions</h3>
          <ul style="line-height: 1.8;">
            ${decisions.map((d) => `<li>${d}</li>`).join("")}
          </ul>
        </section>
      ` : ""}

      ${actionItems.length > 0 ? `
        <section style="margin: 20px 0;">
          <h3 style="color: #1e293b;">🎯 Action Items</h3>
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="background: #f1f5f9;">
              <th style="padding: 10px; text-align: left; border: 1px solid #e2e8f0;">Task</th>
              <th style="padding: 10px; text-align: left; border: 1px solid #e2e8f0;">Owner</th>
              <th style="padding: 10px; text-align: left; border: 1px solid #e2e8f0;">Deadline</th>
              <th style="padding: 10px; text-align: left; border: 1px solid #e2e8f0;">Priority</th>
            </tr>
            ${actionItems.map((item) => `
              <tr>
                <td style="padding: 10px; border: 1px solid #e2e8f0;">${item.task}</td>
                <td style="padding: 10px; border: 1px solid #e2e8f0;">${item.owner}</td>
                <td style="padding: 10px; border: 1px solid #e2e8f0;">${item.deadline}</td>
                <td style="padding: 10px; border: 1px solid #e2e8f0;">
                  <span style="padding: 4px 8px; border-radius: 4px; background: ${
                    item.priority === "High" ? "#fca5a5" :
                    item.priority === "Medium" ? "#fcd34d" : "#d1d5db"
                  };">${item.priority}</span>
                </td>
              </tr>
            `).join("")}
          </table>
        </section>
      ` : ""}

      ${blockers.length > 0 ? `
        <section style="margin: 20px 0;">
          <h3 style="color: #1e293b;">⚠️ Blockers</h3>
          <ul style="line-height: 1.8;">
            ${blockers.map((b) => `<li>${b}</li>`).join("")}
          </ul>
        </section>
      ` : ""}

      <section style="margin: 20px 0; padding: 15px; background: #f0f9ff; border-left: 4px solid #0ea5e9; border-radius: 4px;">
        <h3 style="color: #0c4a6e; margin-top: 0;">💭 Overall Sentiment</h3>
        <p style="margin: 0;">${sentiment}</p>
      </section>

      <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;">
      <p style="font-size: 12px; color: #64748b; text-align: center;">
        Generated by MeetMate AI • Intelligent Meeting Analysis
      </p>
    </div>
  `;
}

export function generateNotificationEmail(meetingType: string): string {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
      <h2 style="color: #0f172a;">✨ Your Meeting Analysis is Ready!</h2>
      
      <p style="font-size: 16px; line-height: 1.6;">
        Your <strong>${meetingType}</strong> meeting has been analyzed and is ready for review.
      </p>

      <div style="margin: 30px 0; text-align: center;">
        <a href="${process.env.VITE_APP_URL || "https://meetmate.ai"}" 
           style="background: #3b82f6; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; font-weight: bold;">
          View Analysis
        </a>
      </div>

      <p style="color: #64748b;">
        Check your meeting summary, decisions, action items, and sentiment analysis in your dashboard.
      </p>

      <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 20px 0;">
      <p style="font-size: 12px; color: #64748b; text-align: center;">
        MeetMate AI • Intelligent Meeting Analysis
      </p>
    </div>
  `;
}
